name: flutter_application_1
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.2
  namer: ^1.0.0
  google_fonts: ^6.1.0
  flutter_native_splash: ^2.3.10
  flutter_launcher_icons: ^0.13.1
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/splash.png
    - assets/icon.png
    - assets/icon_foreground.png

flutter_native_splash:
  color: "#F5E6E3"
  image: assets/splash.png
  android: true
  ios: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#F5E6E3"
  adaptive_icon_foreground: "assets/icon_foreground.png"